---

- name: ELK Pre-Requisites for Ubuntu
  apt:
    name:
      - openjdk-11-jdk
      - wget
      - apt-transport-https
      - curl
      - gnupg2
      - snapd
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: ELK Pre-Requisites for CentOS
  yum:
    name:
      - java-openjdk
      - snapd
    state: latest
    update_cache: yes
  when: ansible_distribution == "CentOS"

- name: Enable Sockets for CentOS
  command: systemctl enable --now snapd.socket
  when: ansible_distribution == "CentOS"
